name: Type-check and test

on:
  push:
    branches:
      - "**"
      - "!master"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: NodeJs aufsetzen
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Type-check
        run: npm run type-check

      - name: Test
        run: npm run test
